# ipython2 --pdb tools/infer_track_sequence.py -- --wts outputs/train/mot17_train_frcnn_02:mot17_train_frcnn_04:mot17_train_frcnn_05:mot17_train_frcnn_09:mot17_train_frcnn_10:mot17_train_frcnn_11/generalized_rcnn/model_final.pkl https://dl.fbaipublicfiles.com/detectron/37697714/12_2017_baselines/e2e_keypoint_rcnn_R-50-FPN_s1x.yaml.08_44_03.qrQ0ph6M/output/train/keypoints_coco_2014_train%3Akeypoints_coco_2014_valminusminival/generalized_rcnn/model_final.pkl --cfg configs/tracking/mask_keypoint_track_rcnn_R-50-FPN_siamese.yaml --preffixes "" sia --im-dir ~/datasets/TUM/rgbd_dataset_freiburg3_walking_halfsphere/rgb --n-colors 2 --output-dir ~/datasets/TUM/rgbd_dataset_freiburg3_walking_halfsphere/dets --output-file ~/datasets/TUM/rgbd_dataset_freiburg3_walking_halfsphere/detections.pkl all-dets show-track

# ipython2 --pdb tools/infer_track_sequence.py -- --wts outputs/train/mot17_train_frcnn_02:mot17_train_frcnn_04:mot17_train_frcnn_05:mot17_train_frcnn_09:mot17_train_frcnn_10:mot17_train_frcnn_11/generalized_rcnn/model_final.pkl --cfg configs/tracking/track_rcnn_R-50-FPN-13.yaml --im-dir ~/datasets/MOT17/train/MOT17-13-FRCNN/img1/ --output-dir outputs/infer_track_sequence/MOT17-13-FRCNN show-track

# ipython2 --pdb tools/infer_track_sequence.py -- --wts outputs/train/mot17_train_frcnn_02:mot17_train_frcnn_04:mot17_train_frcnn_05:mot17_train_frcnn_09:mot17_train_frcnn_10:mot17_train_frcnn_11/generalized_rcnn/model_final.pkl --cfg configs/tracking/track_rcnn_R-50-FPN-13.yaml --im-dir ~/datasets/MOT17/train/MOT17-13-FRCNN/img1/ --output-dir outputs/infer_track_sequence/MOT17-13-FRCNN --proposals ~/datasets/MOT17/train/MOT17-13-FRCNN/det/proposals.pkl show-track

folder=three_people
# folder=new_ye_no_occ

ipython2 --pdb tools/infer_track_sequence.py -- --wts outputs/train/mot17_train_frcnn_02:mot17_train_frcnn_04:mot17_train_frcnn_05:mot17_train_frcnn_09:mot17_train_frcnn_10:mot17_train_frcnn_11/generalized_rcnn/model_final.pkl https://dl.fbaipublicfiles.com/detectron/37697714/12_2017_baselines/e2e_keypoint_rcnn_R-50-FPN_s1x.yaml.08_44_03.qrQ0ph6M/output/train/keypoints_coco_2014_train%3Akeypoints_coco_2014_valminusminival/generalized_rcnn/model_final.pkl --cfg configs/tracking/mask_keypoint_track_rcnn_R-50-FPN_siamese.yaml --preffixes "" sia --im-dir ~/datasets/Princeton\ Tracking\ Benchmark/EvaluationSet/${folder}/rgb --n-colors 2 --output-dir ~/datasets/Princeton\ Tracking\ Benchmark/EvaluationSet/${folder}/dets --output-file ~/datasets/Princeton\ Tracking\ Benchmark/EvaluationSet/${folder}/detections.pkl all-dets show-track
