CONTINUE_ON_ERROR: True
SKIP_EXISTING_WEIGHTS: True
MODEL:
  TYPE: generalized_rcnn
  CONV_BODY: FPN.add_fpn_ResNet50_conv5_body
  NUM_CLASSES: 14
  FASTER_RCNN: True
  RPN_ONLY: True
  TRACKING_ON: True
NUM_GPUS: 1
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  BASE_LR: 0.0025
  GAMMA: 0.1
  MAX_ITER: 180
  STEPS: [0, 120, 160]
FPN:
  FPN_ON: True
  MULTILEVEL_ROIS: True
  MULTILEVEL_RPN: True
FAST_RCNN:
  ROI_BOX_HEAD: head_builder.add_roi_2mlp_head
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 7
  ROI_XFORM_SAMPLING_RATIO: 2
TRAIN:
  WEIGHTS: https://dl.fbaipublicfiles.com/detectron/37697714/12_2017_baselines/e2e_keypoint_rcnn_R-50-FPN_s1x.yaml.08_44_03.qrQ0ph6M/output/train/keypoints_coco_2014_train%3Akeypoints_coco_2014_valminusminival/generalized_rcnn/model_final.pkl
  DATASETS: ('mot17_overtrain',)
  SCALES: (640, )
  BATCH_SIZE_PER_IM: 256
  USE_FLIPPED: False
  FREEZE_CONV_BODY: True
  RPN_PRE_NMS_TOP_N: 10  # Per FPN level
  RPN_POST_NMS_TOP_N: 10
  DEBUG: False
  EPOCH_PERIOD: 5
  ASPECT_GROUPING: False
  AUTO_RESUME: False
TRCNN:
  ROI_TRACKING_HEAD: track_rcnn_heads.add_track_head
  LOSS: CrossEntropyBalanced
  ROI_XFORM_SAMPLING_RATIO: 2
  FRAME_DIST_MIN: 1
  FRAME_DIST_MAX: 36
TEST:
  DATASETS: ('mot17_overtrain',)
  SCALE: 640
  NMS: 0.5
  RPN_PRE_NMS_TOP_N: 100  # Per FPN level
  RPN_POST_NMS_TOP_N: 100
OUTPUT_DIR: outputs
DATA_LOADER:
  MINIBATCH_QUEUE_SIZE: 2
