# SKIP_EXISTING_WEIGHTS: True
SKIP_EXISTING_WEIGHTS: False
CONTINUE_ON_ERROR: True
# DEDUP_BOXES: 0.0
MODEL:
  TYPE: generalized_rcnn
  CONV_BODY: FPN.add_fpn_ResNet50_conv5_body
  # NUM_CLASSES: 2
  # NUM_CLASSES: 14
  NUM_CLASSES: 81
  FASTER_RCNN: True
  # RPN_ONLY: True
  TRACKING_ON: True
NUM_GPUS: 1
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  BASE_LR: 0.0025
  GAMMA: 0.1
  MAX_ITER: 540000
  STEPS: [0, 360000, 480000]
DATA_LOADER:
  MINIBATCH_QUEUE_SIZE: 8
FPN:
  FPN_ON: True
  MULTILEVEL_ROIS: True
  MULTILEVEL_RPN: True
RPN:
  LOSS_ON: False
FAST_RCNN:
  ROI_BOX_HEAD: head_builder.add_roi_2mlp_head
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 7
  ROI_XFORM_SAMPLING_RATIO: 2
  LOSS_ON: False
TRCNN:
  ROI_TRACKING_HEAD: track_rcnn_heads.add_track_head
  LOSS: CrossEntropyBalanced
  ROI_XFORM_SAMPLING_RATIO: 2
  FRAME_DIST_MAX: 2.0
TRAIN:
  WEIGHTS: https://dl.fbaipublicfiles.com/detectron/35859007/12_2017_baselines/e2e_mask_rcnn_R-50-FPN_2x.yaml.01_49_07.By8nQcCH/output/train/coco_2014_train%3Acoco_2014_valminusminival/generalized_rcnn/model_final.pkl
  DATASETS: ('mot17_train_frcnn_02', 'mot17_train_frcnn_04', 'mot17_train_frcnn_05', 'mot17_train_frcnn_09', 'mot17_train_frcnn_10', 'mot17_train_frcnn_11')
  SCALES: (800,)
  MAX_SIZE: 1333
  BATCH_SIZE_PER_IM: 512
  USE_FLIPPED: False
  FREEZE_CONV_BODY: True
  RPN_PRE_NMS_TOP_N: 600  # Per FPN level
  RPN_POST_NMS_TOP_N: 300
  DEBUG: False
  ASPECT_GROUPING: False
  EPOCH_PERIOD: 100
  SNAPSHOT_ITERS: 1000
TEST:
  DATASETS: ('mot17_train_frcnn_13',)
  SCALE: 800
  MAX_SIZE: 1333
  NMS: 0.5
  RPN_PRE_NMS_TOP_N: 1000  # Per FPN level
  RPN_POST_NMS_TOP_N: 1000
OUTPUT_DIR: outputs
